# Generated by Django 4.1.2 on 2022-10-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='name',
            new_name='quantity',
        ),
    ]
