# Generated by Django 4.1.2 on 2022-10-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_rename_name_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
